config/routes.rb
Railtweet::Application.routes.draw do
  resources :trackings

  resources :vehicles

  resources :vehicle_stop_delays

  resources :vehicle_stops

  resources :connection_stops

  resources :connections

  resources :one_way_trips

  resources :stations

  resources :users

  get "public/index"
  root :to => "public#index"
  
  match "/trip_info" => "public#trip_info"
  
  match "/update" => "public#update", :as => :update_twitter
  match "/auth/twitter/callback" => "session#create"
  match "/signout" => "session#destroy", :as => :signout
  
end

app/models/vehicle_stop_delay.rb
class VehicleStopDelay < ActiveRecord::Base
  belongs_to :vehicle_stop
  
  before_save :update_was_cancelled
  
  def update_was_cancelled
    if self.platform == "NA"
      self.was_cancelled = true
    end
  end
end

app/controllers/vehicle_stop_delays_controller.rb
class VehicleStopDelaysController < ApplicationController
  before_filter :authenticate, :set_admin
  
  # GET /vehicle_stop_delays
  # GET /vehicle_stop_delays.xml
  def index
    @vehicle_stop_delays = VehicleStopDelay.all
    respond_with(@vehicle_stop_delays)
  end

  # GET /vehicle_stop_delays/1
  # GET /vehicle_stop_delays/1.xml
  def show
    @vehicle_stop_delay = VehicleStopDelay.find(params[:id])
    respond_with(@vehicle_stop_delay)
  end

  # GET /vehicle_stop_delays/new
  # GET /vehicle_stop_delays/new.xml
  def new
    @vehicle_stop_delay = VehicleStopDelay.new
    respond_with(@vehicle_stop_delay)
  end

  # GET /vehicle_stop_delays/1/edit
  def edit
    @vehicle_stop_delay = VehicleStopDelay.find(params[:id])
  end

  # POST /vehicle_stop_delays
  # POST /vehicle_stop_delays.xml
  def create
    @vehicle_stop_delay = VehicleStopDelay.new(params[:vehicle_stop_delay])
    flash[:notice] = 'VehicleStopDelay was successfully created.' if @vehicle_stop_delay.save
    respond_with(@vehicle_stop_delay)
  end

  # PUT /vehicle_stop_delays/1
  # PUT /vehicle_stop_delays/1.xml
  def update
    @vehicle_stop_delay = VehicleStopDelay.find(params[:id])
    flash[:notice] = 'VehicleStopDelay was successfully updated.' if @vehicle_stop_delay.update_attributes(params[:vehicle_stop_delay])
    respond_with(@vehicle_stop_delay)
  end

  # DELETE /vehicle_stop_delays/1
  # DELETE /vehicle_stop_delays/1.xml
  def destroy
    @vehicle_stop_delay = VehicleStopDelay.find(params[:id])
    @vehicle_stop_delay.destroy
    respond_with(@vehicle_stop_delay)
  end
end

app/helpers/vehicle_stop_delays_helper.rb
module VehicleStopDelaysHelper
end

app/views/vehicle_stop_delays/_form.html.haml
= form_for @vehicle_stop_delay do |f|
  -if @vehicle_stop_delay.errors.any?
    #error_explanation
      %h2= "#{pluralize(@vehicle_stop_delay.errors.count, "error")} prohibited this vehicle_stop_delay from being saved:"
      %ul
        - @vehicle_stop_delay.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :vehicle_stop_id
    = f.text_field :vehicle_stop_id
  .field
    = f.label :delay
    = f.text_field :delay
  .field
    = f.label :is_cancelled
    = f.check_box :is_cancelled
  .actions
    = f.submit 'Save'

app/views/vehicle_stop_delays/edit.html.haml
%h1 Editing vehicle_stop_delay

= render 'form'

= link_to 'Show', @vehicle_stop_delay
\|
= link_to 'Back', vehicle_stop_delays_path

app/views/vehicle_stop_delays/index.html.haml
%h1 Listing vehicle_stop_delays

%table
  %tr
    %th Vehicle stop
    %th Delay
    %th Is cancelled
    %th
    %th
    %th

  - @vehicle_stop_delays.each do |vehicle_stop_delay|
    %tr
      %td= vehicle_stop_delay.vehicle_stop_id
      %td= vehicle_stop_delay.delay
      %td= vehicle_stop_delay.is_cancelled
      %td= link_to 'Show', vehicle_stop_delay
      %td= link_to 'Edit', edit_vehicle_stop_delay_path(vehicle_stop_delay)
      %td= link_to 'Destroy', vehicle_stop_delay, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Vehicle stop delay', new_vehicle_stop_delay_path

app/views/vehicle_stop_delays/new.html.haml
%h1 New vehicle_stop_delay

= render 'form'

= link_to 'Back', vehicle_stop_delays_path

app/views/vehicle_stop_delays/show.html.haml
%p#notice= notice

%p
  %b Vehicle stop:
  = @vehicle_stop_delay.vehicle_stop_id
%p
  %b Delay:
  = @vehicle_stop_delay.delay
%p
  %b Is cancelled:
  = @vehicle_stop_delay.is_cancelled

= link_to 'Edit', edit_vehicle_stop_delay_path(@vehicle_stop_delay)
\|
= link_to 'Back', vehicle_stop_delays_path