config/routes.rb
Railtweet::Application.routes.draw do
  resources :trackings

  resources :vehicles

  resources :vehicle_stop_delays

  resources :vehicle_stops

  resources :connection_stops

  resources :connections

  resources :one_way_trips

  resources :stations

  resources :users

  get "public/index"
  root :to => "public#index"
  
  match "/trip_info" => "public#trip_info"
  
  match "/update" => "public#update", :as => :update_twitter
  match "/auth/twitter/callback" => "session#create"
  match "/signout" => "session#destroy", :as => :signout
  
end

app/models/one_way_trip.rb
class OneWayTrip < ActiveRecord::Base
  belongs_to :from_station, :class_name => "Station"
  belongs_to :to_station, :class_name => "Station"
  has_many :connections
  
  def name
    "#{self.from_station.code} - #{self.to_station.code}"
  end
end

app/controllers/one_way_trips_controller.rb
class OneWayTripsController < ApplicationController
  before_filter :authenticate, :set_admin
  
  # GET /one_way_trips
  # GET /one_way_trips.xml
  def index
    @search = OneWayTrip.search(params[:search])
    @one_way_trips = @search.paginate(:per_page => 40, :page=>params[:page])
    respond_with(@one_way_trips)
  end

  # GET /one_way_trips/1
  # GET /one_way_trips/1.xml
  def show
    @one_way_trip = OneWayTrip.find(params[:id])
    respond_with(@one_way_trip)
  end

  # GET /one_way_trips/new
  # GET /one_way_trips/new.xml
  def new
    @one_way_trip = OneWayTrip.new
    respond_with(@one_way_trip)
  end

  # GET /one_way_trips/1/edit
  def edit
    @one_way_trip = OneWayTrip.find(params[:id])
  end

  # POST /one_way_trips
  # POST /one_way_trips.xml
  def create
    @one_way_trip = OneWayTrip.new(params[:one_way_trip])
    flash[:notice] = 'OneWayTrip was successfully created.' if @one_way_trip.save
    respond_with(@one_way_trip)
  end

  # PUT /one_way_trips/1
  # PUT /one_way_trips/1.xml
  def update
    @one_way_trip = OneWayTrip.find(params[:id])
    flash[:notice] = 'OneWayTrip was successfully updated.' if @one_way_trip.update_attributes(params[:one_way_trip])
    respond_with(@one_way_trip)
  end

  # DELETE /one_way_trips/1
  # DELETE /one_way_trips/1.xml
  def destroy
    @one_way_trip = OneWayTrip.find(params[:id])
    @one_way_trip.destroy
    respond_with(@one_way_trip)
  end
end

app/helpers/one_way_trips_helper.rb
module OneWayTripsHelper
end

app/views/one_way_trips/_form.html.haml
= simple_form_for @one_way_trip do |f|
  =f.association :from_station, :label => "from Code", :collection=>Station.select(current_language), :label_method => "name_#{current_language}", :input_html => { :disabled => is_disabled }
  .spacer
  =f.association :to_station, :label => "to Code", :collection=>Station.select(current_language), :label_method => "name_#{current_language}", :input_html => { :disabled => is_disabled }
  .spacer


  = f.submit 'Save'

app/views/one_way_trips/edit.html.haml
#back
  = link_to 'Show', @one_way_trip
  \|
  = link_to 'List', one_way_trips_path
  
  = render 'form', :is_disabled => false

app/views/one_way_trips/index.html.haml
#back
  = link_to 'New One way trip', new_one_way_trip_path
  
  = simple_form_for @search do |f|
    #search
      = f.input :from_station_id_equals, :collection=>Station.select(current_language), :label_method => "name_#{current_language}", :required => false, :label => "From"
      .spacer
      
      = f.input :to_station_id_equals, :collection=>Station.select(current_language), :label_method => "name_#{current_language}", :required => false, :label => "To"
      .spacer

      = f.submit "Zoek"
      .spacer

    .pagination
      = will_paginate @one_way_trips
    .spacer
  
  %table
    %tr
      %th 
        = sort_link @search, "from_station_name_#{current_language}", "From"
      %th
        = sort_link @search, "to_station_name_#{current_language}", "To"
      %th
      %th
      %th

    - @one_way_trips.each do |one_way_trip|
      %tr
        %td= one_way_trip.from_station.try "name_#{current_language}"
        %td= one_way_trip.to_station.try "name_#{current_language}"
        %td= link_to 'Show', one_way_trip
        %td= link_to 'Edit', edit_one_way_trip_path(one_way_trip)
        %td= link_to 'Destroy', one_way_trip, :confirm => 'Are you sure?', :method => :delete

  %br

app/views/one_way_trips/new.html.haml
#back
  = link_to 'List', one_way_trips_path

  = render 'form', :is_disabled => false

app/views/one_way_trips/show.html.haml
#back
  = link_to 'Edit', edit_one_way_trip_path(@one_way_trip)
  \|
  = link_to 'List', one_way_trips_path

  = render 'form', :is_disabled => true