config/routes.rb
Railtweet::Application.routes.draw do
  resources :trackings

  resources :vehicles

  resources :vehicle_stop_delays

  resources :vehicle_stops

  resources :connection_stops

  resources :connections

  resources :one_way_trips

  resources :stations

  resources :users

  get "public/index"
  root :to => "public#index"
  
  match "/trip_info" => "public#trip_info"
  
  match "/update" => "public#update", :as => :update_twitter
  match "/auth/twitter/callback" => "session#create"
  match "/signout" => "session#destroy", :as => :signout
  
end

app/models/vehicle.rb
class Vehicle < ActiveRecord::Base
  has_many :vehicle_stops
  belongs_to :from_station, :class_name => "Station"
  belongs_to :to_station, :class_name => "Station"
  
  before_save :update_train_type_and_train_number
  
  validates :complete_number, :uniqueness => true
  validates :train_number, :uniqueness => true
  
  def update_train_type_and_train_number
    self.train_type = self.complete_number.split(".").last.match(/\D+/)[0]
    self.train_number = self.complete_number.split(".").last.match(/\d+/)[0]
    if self.departure_hour and self.departure_min
      self.departure_time = '%02d:%02d' % [self.departure_hour,self.departure_min]
    end
  end
  
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  before_filter :authenticate, :set_admin
  
  # GET /vehicles
  # GET /vehicles.xml
  def index
    @search = Vehicle.search(params[:search])
    @vehicles = @search.paginate(:per_page => 40, :page=>params[:page])
    respond_with(@vehicles)
  end

  # GET /vehicles/1
  # GET /vehicles/1.xml
  def show
    @vehicle = Vehicle.find(params[:id])
    respond_with(@vehicle)
  end

  # GET /vehicles/new
  # GET /vehicles/new.xml
  def new
    @vehicle = Vehicle.new
    respond_with(@vehicle)
  end

  # GET /vehicles/1/edit
  def edit
    @vehicle = Vehicle.find(params[:id])
  end

  # POST /vehicles
  # POST /vehicles.xml
  def create
    @vehicle = Vehicle.new(params[:vehicle])
    flash[:notice] = 'Vehicle was successfully created.' if @vehicle.save
    respond_with(@vehicle)
  end

  # PUT /vehicles/1
  # PUT /vehicles/1.xml
  def update
    @vehicle = Vehicle.find(params[:id])
    flash[:notice] = 'Vehicle was successfully updated.' if @vehicle.update_attributes(params[:vehicle])
    respond_with(@vehicle)
  end

  # DELETE /vehicles/1
  # DELETE /vehicles/1.xml
  def destroy
    @vehicle = Vehicle.find(params[:id])
    @vehicle.destroy
    respond_with(@vehicle)
  end
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/vehicles/_form.html.haml
= form_for @vehicle do |f|
  -if @vehicle.errors.any?
    #error_explanation
      %h2= "#{pluralize(@vehicle.errors.count, "error")} prohibited this vehicle from being saved:"
      %ul
        - @vehicle.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :complete_number
    = f.text_field :complete_number
  .field
    = f.label :train_type
    = f.text_field :train_type
  .field
    = f.label :train_number
    = f.text_field :train_number
  .actions
    = f.submit 'Save'

app/views/vehicles/edit.html.haml
%h1 Editing vehicle

= render 'form'

= link_to 'Show', @vehicle
\|
= link_to 'Back', vehicles_path

app/views/vehicles/index.html.haml
#back
  = link_to 'New Vehicle', new_vehicle_path

  = simple_form_for @search do |f|
    #search
      = f.input :train_number_contains, :required => false, :label => "Train Number"
      = f.input :train_type_contains, :required => false, :label => "Train Type"
      .spacer
      = f.input :from_station_id_equals, :collection=>Station.select(current_language), :label_method => "name_#{current_language}", :required => false, :label => "From"
      .spacer
      = f.input :to_station_id_equals, :collection=>Station.select(current_language), :label_method => "name_#{current_language}", :required => false, :label => "To"
      .spacer
      

      = f.submit "Zoek"
      .spacer

    .pagination
      = will_paginate @users
    .spacer

    %table
      %tr
        %th 
          = sort_link @search, :complete_number
        %th 
          = sort_link @search, :train_type, "Type"
        %th 
          = sort_link @search, :train_number, "Number"
        %th
          = sort_link @search, "from_station_name_#{current_language}", "From"
        %th
          = sort_link @search, "from_station_name_#{current_language}", "To"
        %th
          = sort_link @search, :departure_time, "Time"
        %th
          = sort_link @search, :number_of_stops, "Stops"


        %th
        %th
        %th

      - @vehicles.each do |vehicle|
        %tr
          %td= vehicle.complete_number
          %td= vehicle.train_type
          %td= vehicle.train_number
          %td= vehicle.from_station.try "name_#{current_language}"
          %td= vehicle.to_station.try "name_#{current_language}"
          %td= vehicle.departure_time
          %td= vehicle.number_of_stops
          
          %td= link_to 'Show', vehicle
          %td= link_to 'Edit', edit_vehicle_path(vehicle)
          %td= link_to 'Destroy', vehicle, :confirm => 'Are you sure?', :method => :delete

app/views/vehicles/new.html.haml
%h1 New vehicle

= render 'form'

= link_to 'Back', vehicles_path

app/views/vehicles/show.html.haml
%p#notice= notice

%p
  %b Complete number:
  = @vehicle.complete_number
%p
  %b Train type:
  = @vehicle.train_type
%p
  %b Train number:
  = @vehicle.train_number

= link_to 'Edit', edit_vehicle_path(@vehicle)
\|
= link_to 'Back', vehicles_path