config/routes.rb
Railtweet::Application.routes.draw do
  resources :trackings

  resources :vehicles

  resources :vehicle_stop_delays

  resources :vehicle_stops

  resources :connection_stops

  resources :connections

  resources :one_way_trips

  resources :stations

  resources :users

  get "public/index"
  root :to => "public#index"
  
  match "/trip_info" => "public#trip_info"
  
  match "/update" => "public#update", :as => :update_twitter
  match "/auth/twitter/callback" => "session#create"
  match "/signout" => "session#destroy", :as => :signout
  
end

app/views/layouts/_admin_menu.html.haml
.item.left
  = link_to("Users", users_url)
.item.left
  = link_to("One Way Trips", one_way_trips_url)
.item.left
  = link_to("Connections", connections_url)
.item.left
  = link_to("Stations", stations_url)
.item.left
  = link_to("Vehicles", vehicles_url)

app/views/layouts/application.html.haml
!!! Strict
%html
  %head
    %title Railtweet
    = stylesheet_link_tag :all
    = javascript_include_tag :defaults
    = csrf_meta_tag

  %body
    #header_bar
      %header
        .item.railtweet.left
          = link_to("RailTweet", root_url)
        - if is_admin
          = render '/layouts/admin_menu'
        - if current_user
          .item.right
            = link_to t('signout'), signout_path
          .name_item.right
            = current_user.name
          .image_item.right
            = image_tag current_user.image
        - else
          .item.right
            = link_to t('signin_with_twitter'), "/auth/twitter"
        .item.right
          = link_to "nl", :language => 'nl'
        .item.right
          = link_to "fr", :language => 'fr'
        .item.right
          = link_to "en", :language => 'en'
    %section
      - flash.each do |name, msg|
        #flash
          = content_tag :div, msg, :class=> "#{name}"
      = yield
    